### ISSUE TITLE
Final changes before test on rasta

### ISSUE THREAD

**Issue by adrosenbaum** [Clinical-Genomics/mutacc#31]
I have some improvements and testing to do before mutacc is ready to test on rasta. I think I will be done this week. The README.md is updated on the master branch covering most of the functionalities. you can read it when you have time and we can discuss what needs to be done next after the weekend.

Have a nice weekend!

**Comment by henrikstranneheim** [comment]
Great! Use the coverall report as a guide to write the unit tests. I think the software is starting to look great. Let’s make it a goal for next week to get up and running on Rasta with a few real cases. Have a nice weekend!
